// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC9jjSsl0iiaDBHStJSWJGfRBJEtY0bus',
    appId: '1:75030496280:web:b9a2d74a981453c0eaef6d',
    messagingSenderId: '75030496280',
    projectId: 'helpbeacon-915e5',
    authDomain: 'helpbeacon-915e5.firebaseapp.com',
    storageBucket: 'helpbeacon-915e5.firebasestorage.app',
    measurementId: 'G-K22GVLEKH2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwONcGhuGqClJ5dtI8X_e2X7CyQCZa9eQ',
    appId: '1:75030496280:android:063fa272f76d8603eaef6d',
    messagingSenderId: '75030496280',
    projectId: 'helpbeacon-915e5',
    storageBucket: 'helpbeacon-915e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm1WX7jZ7ZKfx4EzOXgYR6-_TcrWQ9Fuc',
    appId: '1:75030496280:ios:208ccf3e471d2b1eeaef6d',
    messagingSenderId: '75030496280',
    projectId: 'helpbeacon-915e5',
    storageBucket: 'helpbeacon-915e5.firebasestorage.app',
    iosBundleId: 'com.example.helpbeacon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm1WX7jZ7ZKfx4EzOXgYR6-_TcrWQ9Fuc',
    appId: '1:75030496280:ios:208ccf3e471d2b1eeaef6d',
    messagingSenderId: '75030496280',
    projectId: 'helpbeacon-915e5',
    storageBucket: 'helpbeacon-915e5.firebasestorage.app',
    iosBundleId: 'com.example.helpbeacon',
  );
}
